name: Notify ntfy

on:
  push:
    branches:
      - main   # change if your branch is different

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        run: |
          curl -H "Title: Repo Updated" \
               -H "Priority: default" \
               -d "New push to main by ${{ github.actor }}: ${{ github.event.head_commit.message }}" \
               https://ntfy.sh/HarperandJakobgithubrepo2026
